services:
  - type: web
    name: portfolio-frontend
    runtime: static
    buildCommand: npm install && npm run build
    staticPublishPath: build
    envVars:
      - key: REACT_APP_API_BASE
        value: https://portfolio-backend-ro4m.onrender.com
